name: Build KImageFormats
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            qtVersion: '5.15.2'
            buildArch: 'X64'
          - os: macos-14
            qtVersion: '6.5.3'
            buildArch: 'Universal'
          - os: macos-14
            qtVersion: '5.15.2'
            buildArch: 'X64'
          - os: windows-2022
            qtVersion: '6.5.3'
            qtArch: 'win64_msvc2019_64'
            buildArch: 'X64'
          - os: windows-2022
            qtVersion: '6.5.3'
            qtArch: 'win64_msvc2019_arm64'
            buildArch: 'Arm64'
          - os: windows-2022
            qtVersion: '5.15.2'
            qtArch: 'win32_msvc2019'
            buildArch: 'X86'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{ matrix.qtVersion }}
          arch: ${{ matrix.qtArch }}

      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'c4467cb686f92671f0172aa8299a77d908175b4e'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1
        env:
          buildArch: ${{ matrix.buildArch }}

      - name: 'Upload Artifact'
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: KImageFormats-${{ runner.os }}-${{ matrix.qtVersion }}-${{ matrix.buildArch }}
          path: kimageformats/output

      - name: 'Zip Artifact'
        if: github.ref == 'refs/heads/master'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: kimageformats/output/
          filename: "KImageFormats-${{ runner.os }}-${{ matrix.qtVersion }}-${{ matrix.buildArch }}.zip"

      - name: 'Upload to continous release'
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'cont'
          files: KImageFormats-*.zip
