name: Build KImageFormats
on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            vers: '5.15.2'
          - os: macos-12
            vers: '6.5.3'
            universalBinary: 'true'
          - os: macos-12
            vers: '5.15.2'
          - os: windows-2022
            vers: '6.5.3'
            forceWin32: 'false'
            arch: 'win64_msvc2019_64'
          - os: windows-2022
            vers: '5.15.2'
            forceWin32: 'true'
            arch: 'win32_msvc2019'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cache: true
          version: ${{ matrix.vers }}
          arch: ${{ matrix.arch }}

      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '326d8b43e365352ba3ccadf388d989082fe0f2a6'

      - name: Build KImageFormats (just one big step for now)
        run: pwsh pwsh/buildkimageformats.ps1
        env:
          forceWin32: ${{ matrix.forceWin32 }}
          universalBinary: ${{ matrix.universalBinary }}

      - name: 'Upload Artifact'
        if: github.ref != 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}
          path: kimageformats/output

      - name: 'Zip Artifact'
        if: github.ref == 'refs/heads/master'
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          path: kimageformats/output/
          filename: "kimageformats-${{ matrix.os }}-${{ matrix.vers }}${{ matrix.arch && format('-{0}', matrix.arch) || '' }}.zip"

      - name: 'Upload to continous release'
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 'cont'
          files: kimageformats-*.zip
